// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cities.sql

package database

import (
	"context"
)

const activeCityCount = `-- name: ActiveCityCount :one
SELECT COUNT(*)
FROM cities
WHERE is_active = TRUE
`

func (q *Queries) ActiveCityCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, activeCityCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const citiesCount = `-- name: CitiesCount :one
SELECT COUNT(*)
FROM cities
`

func (q *Queries) CitiesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, citiesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCity = `-- name: CreateCity :one
INSERT INTO cities(name_en, name_ar, is_active)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateCityParams struct {
	NameEn   string
	NameAr   string
	IsActive bool
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCity, arg.NameEn, arg.NameAr, arg.IsActive)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCity = `-- name: DeleteCity :exec
DELETE
FROM cities
WHERE id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCity, id)
	return err
}

const filterAllCities = `-- name: FilterAllCities :many
SELECT id, name_en, name_ar, is_active
FROM cities
WHERE name_en ILIKE $3 or name_ar ILIKE $3
ORDER BY id
LIMIT $1 OFFSET $2
`

type FilterAllCitiesParams struct {
	Limit  int64
	Offset int64
	Query  string
}

func (q *Queries) FilterAllCities(ctx context.Context, arg FilterAllCitiesParams) ([]City, error) {
	rows, err := q.db.Query(ctx, filterAllCities, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.NameEn,
			&i.NameAr,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCity = `-- name: ListActiveCity :many
SELECT id, name_en, name_ar, is_active
FROM cities
WHERE is_active = TRUE
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListActiveCityParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListActiveCity(ctx context.Context, arg ListActiveCityParams) ([]City, error) {
	rows, err := q.db.Query(ctx, listActiveCity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.NameEn,
			&i.NameAr,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCities = `-- name: ListAllCities :many
SELECT id, name_en, name_ar, is_active
FROM cities
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListAllCitiesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAllCities(ctx context.Context, arg ListAllCitiesParams) ([]City, error) {
	rows, err := q.db.Query(ctx, listAllCities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.NameEn,
			&i.NameAr,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :one
UPDATE cities
SET name_en=$1,
    name_ar=$2,
    is_active=$3
WHERE id = $4
RETURNING id, name_en, name_ar, is_active
`

type UpdateCityParams struct {
	NameEn   string
	NameAr   string
	IsActive bool
	ID       int64
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, updateCity,
		arg.NameEn,
		arg.NameAr,
		arg.IsActive,
		arg.ID,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.NameEn,
		&i.NameAr,
		&i.IsActive,
	)
	return i, err
}
